/* AUTO-GENERATED by tools/video_to_sprites.py — do not edit. */
#ifndef ASSETS_RESPONDING_FRAMES_H_
#define ASSETS_RESPONDING_FRAMES_H_

#include <stdint.h>
#include <stddef.h>

#include "sprite_types.h"

#define RESPONDING_WIDTH   800
#define RESPONDING_HEIGHT  480
#define RESPONDING_FPS     24
#define RESPONDING_FRAMES  72

/* Concatenated LZ4 block-format payload, 72 frames. */
extern const uint8_t responding_lz4_blob[];

extern const struct sprite_frame_rec responding_frames[72];

#endif /* ASSETS_RESPONDING_FRAMES_H_ */
