/* AUTO-GENERATED by tools/video_to_sprites.py — do not edit. */
#ifndef ASSETS_THINKING_FRAMES_H_
#define ASSETS_THINKING_FRAMES_H_

#include <stdint.h>
#include <stddef.h>

#include "sprite_types.h"

#define THINKING_WIDTH   400
#define THINKING_HEIGHT  240
#define THINKING_FPS     24
#define THINKING_FRAMES  72

/* Concatenated LZ4 block-format payload, 72 frames. */
extern const uint8_t thinking_lz4_blob[];

extern const struct sprite_frame_rec thinking_frames[72];

#endif /* ASSETS_THINKING_FRAMES_H_ */
