/*
 * PSE84 Voice Assistant — sprite-sheet playback.
 *
 * Plays a per-state LZ4-compressed RGB565 sprite sheet (generated by
 * tools/video_to_sprites.py) on a single LVGL lv_image widget. Each
 * sprite_sheet wraps:
 *   - a concatenated LZ4 block-format payload,
 *   - a per-frame { offset, compressed-length, raw-length } table,
 *   - width / height / fps metadata.
 *
 * Only one sheet plays at a time; sprites_play() stops any previous
 * timer, loads the sheet, decompresses frame 0 into the shared scratch
 * framebuffer, and installs a periodic lv_timer that advances the frame
 * index and triggers a redraw.
 *
 * The scratch framebuffer is the largest single allocation (800*480*2 =
 * 768 KB at tier A); it lives in the LV_MEM pool via lv_draw_buf_create.
 * sprites_stop() leaves the last-rendered frame on screen and stops the
 * timer only — the buffer stays allocated for the lifetime of the app.
 */

#ifndef PSE84_ASSISTANT_SPRITES_H_
#define PSE84_ASSISTANT_SPRITES_H_

#ifdef CONFIG_APP_ANIMATION_SPRITES

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <lvgl.h>

#include "sprite_types.h"

struct sprite_sheet {
	const char *name;
	const uint8_t *lz4_blob;
	const struct sprite_frame_rec *frames;
	uint32_t n_frames;
	uint16_t width;
	uint16_t height;
	uint16_t fps;
	uint16_t zoom;   /* 256 = 1.0x, 512 = 2.0x (tier B upscale). */
};

/* Build-time stats published for the banner / runtime reporting. */
struct sprite_stats {
	uint32_t frames_decoded;     /* lifetime counter */
	uint32_t last_decomp_cycles; /* k_cycle_get_32 delta for last frame */
	uint32_t total_decomp_cycles;/* accumulator for avg */
};

/* Allocate the scratch framebuffer and prepare the lv_image widget on
 * `parent`. Idempotent. Returns 0 on success.
 */
int sprites_init(lv_obj_t *parent);

/* Start playback of `sheet`. Pass NULL to blank the widget. */
void sprites_play(const struct sprite_sheet *sheet);

/* Stop the playback timer. Current frame stays on screen. */
void sprites_stop(void);

/* Snapshot of decode stats. Returns via out pointer (caller owns). */
void sprites_get_stats(struct sprite_stats *out);

/* Sheets generated by tools/video_to_sprites.py — one per state. */
extern const struct sprite_sheet sprite_sheet_idle;
extern const struct sprite_sheet sprite_sheet_listening;
extern const struct sprite_sheet sprite_sheet_thinking;
extern const struct sprite_sheet sprite_sheet_responding;

#endif /* CONFIG_APP_ANIMATION_SPRITES */

#endif /* PSE84_ASSISTANT_SPRITES_H_ */
