/* AUTO-GENERATED by tools/video_to_sprites.py — do not edit. */
#ifndef ASSETS_LISTENING_FRAMES_H_
#define ASSETS_LISTENING_FRAMES_H_

#include <stdint.h>
#include <stddef.h>

#include "sprite_types.h"

#define LISTENING_WIDTH   800
#define LISTENING_HEIGHT  480
#define LISTENING_FPS     24
#define LISTENING_FRAMES  72

/* Concatenated LZ4 block-format payload, 72 frames. */
extern const uint8_t listening_lz4_blob[];

extern const struct sprite_frame_rec listening_frames[72];

#endif /* ASSETS_LISTENING_FRAMES_H_ */
