/* AUTO-GENERATED by tools/video_to_sprites.py — do not edit. */
#ifndef ASSETS_IDLE_FRAMES_H_
#define ASSETS_IDLE_FRAMES_H_

#include <stdint.h>
#include <stddef.h>

#include "sprite_types.h"

#define IDLE_WIDTH   400
#define IDLE_HEIGHT  240
#define IDLE_FPS     24
#define IDLE_FRAMES  72

/* Concatenated LZ4 block-format payload, 72 frames. */
extern const uint8_t idle_lz4_blob[];

extern const struct sprite_frame_rec idle_frames[72];

#endif /* ASSETS_IDLE_FRAMES_H_ */
